name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Validate Commits Messages
        if: github.event_name == 'pull_request'
        run: npx --no-install commitlint --verbose --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }}

      - name: Clean build artifacts
        run: npm run clean

      - name: Rebuild workspace links
        run: npm install --workspaces

      - name: Test build
        id: npm-build
        run: npm run build -- --no-cache

      - name: Lint
        id: npm-lint
        run: npm run lint -- --no-cache

      - name: Test
        id: npm-test
        run: npm run test
